import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-dvh font-sans antialiased")}>
        <div className="fixed z-50 hidden min-h-dvh w-full items-center justify-center bg-red-500 text-white sm:flex">
          This app is for mobile as of right now.
        </div>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
